{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName | default (printf "%s-secrets" (include "uap-scraper.fullname" .)) }}
  labels:
    {{- include "uap-scraper.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.gcpServiceAccountKeyJson }}
  gcp-key.json: {{ .Values.secrets.gcpServiceAccountKeyJson | quote }}
  {{- end }}
  {{- if .Values.secrets.kaggleUsername }}
  KAGGLE_USERNAME: {{ .Values.secrets.kaggleUsername | quote }}
  {{- end }}
  {{- if .Values.secrets.kaggleKey }}
  KAGGLE_KEY: {{ .Values.secrets.kaggleKey | quote }}
  {{- end }}
{{- end }}
